name: zip_diff
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  archive: ^3.3.9
  cross_file: ^0.3.3+5
  cupertino_icons: ^1.0.2
  desktop_drop: ^0.4.3
  file_picker: ^5.5.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope.ttf

flutter_launcher_icons:
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"
